/**:
  ros__parameters:
    gain_multiplier: 3.0
    base_linear_speed: 0.5
    base_angular_speed: 0.8
    base_idle_drain_a: 1.0
    base_move_drain_per_ms: 8.0
    base_turn_drain_per_rads: 3.0

battery_node:
  ros__parameters:
    battery_capacity_ah: 1.0
    battery_voltage: 12.0
    publish_rate_hz: 10.0
    charge_rate_a: 40.0
    charging_radius: 0.6
    stationary_thresh: 0.05
    charging_station_x: [-20.0, 20.0]
    charging_station_y: [0.0, 0.0]

    color_idle.ambient: [0.0, 0.8, 0.0, 1.0]
    color_idle.diffuse: [0.0, 0.0, 0.0, 1.0]
    color_idle.specular: [0.0, 0.0, 0.0, 1.0]

    color_charging.ambient: [0.0, 0.0, 0.9, 1.0]
    color_charging.diffuse: [0.0, 0.0, 0.9, 1.0]
    color_charging.specular: [0.0, 0.0, 0.9, 1.0]

    color_full.ambient: [0.0, 0.4, 0.4, 0.2]
    color_full.diffuse: [0.0, 0.9, 0.9, 0.2]
    color_full.specular: [0.0, 1.0, 1.0, 1.0]

move5:
  ros__parameters:
    stop_distance: 1.0
    angle_tol: 0.05
    dist_tol: 0.20
    dwell_time: 5.0
    visited_radius: 0.8
    detection_timeout: 1.5

auto_recharge_node:
  ros__parameters:
    low_battery_threshold: 0.25
    arrived_radius: 0.50
    
    k_linear: 0.4
    k_angular: 1.6
    turn_only_angle: 0.25
    drive_angle: 0.40
    control_hz: 20.0
    charging_station_x: [-20.0, 20.0]
    charging_station_y: [0.0, 0.0]